name: frontend
description: A product price calculator app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  http: ^1.3.0
  path_provider: ^2.1.1  # For accessing app directories
  crypto: ^3.0.3  # For generating MD5 hashes
  carousel_slider: ^5.0.0
  video_player: ^2.7.2
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14  # For opening URLs in browser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  build_runner: ^2.1.0
  flutter_gen_runner: ^5.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/product_detector.js
    - assets/images/
    - assets/images/products/
    - assets/video/
    - assets/images/brands/
  
  # Removed the font declarations since we're using Google Fonts

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/foz.jpg"
  adaptive_icon_background: "#FFFFFF" # Optional for Android